import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { Fault, StructureNode, EquipmentType, OrganizationSettings } from '../types/cmms.ts';
import { formatMinutes } from './timeCalculations.ts';

export interface PDFReportOptions {
  title: string;
  reportType: 'monthly' | 'equipment' | 'structure' | 'history';
  dateRangeStr?: string;
  generatedBy: string;
  settings: OrganizationSettings;
  faults: Fault[];
  nodes: StructureNode[];
  equipmentTypes: EquipmentType[];
  kpis?: {
    total: number;
    open: number;
    resolved: number;
    closed: number;
    relevant: number;
    nonRelevant: number;
    avgTTR: number;
    totalDowntime: number;
  };
  filterSummary?: string;
}

export function generatePDFReport(options: PDFReportOptions): void {
  const { title, reportType, dateRangeStr, generatedBy, settings, faults, nodes, equipmentTypes, kpis, filterSummary } = options;

  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4'
  });

  const nodeMap = new Map(nodes.map(n => [n.id, n.name]));
  const eqTypeMap = new Map(equipmentTypes.map(t => [t.id, t.code]));

  // Brand colors
  const primaryColor: [number, number, number] = [30, 41, 59]; // slate-800
  const accentColor: [number, number, number] = [14, 116, 144]; // cyan-700
  const headerBg: [number, number, number] = [241, 245, 249]; // slate-100

  // 1. Header & Title Block
  doc.setFillColor(...headerBg);
  doc.rect(0, 0, 210, 38, 'F');

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(16);
  doc.setTextColor(...primaryColor);
  doc.text(settings.organizationName || 'ApexCMMS Enterprise', 14, 14);

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(100, 116, 139);
  doc.text(settings.maintenanceDepartment || 'Maintenance Operations Division', 14, 20);

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(14);
  doc.setTextColor(...accentColor);
  doc.text(title.toUpperCase(), 14, 30);

  // Metadata block (top right)
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  doc.setTextColor(71, 85, 105);
  doc.text(`Generated: ${new Date().toLocaleString()}`, 196, 14, { align: 'right' });
  doc.text(`Generated By: ${generatedBy}`, 196, 19, { align: 'right' });
  if (dateRangeStr) {
    doc.text(`Period: ${dateRangeStr}`, 196, 24, { align: 'right' });
  }
  if (filterSummary) {
    doc.text(`Filters: ${filterSummary}`, 196, 29, { align: 'right' });
  }

  let currentY = 44;

  // 2. KPI Summary Cards (if KPIs provided)
  if (kpis) {
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(11);
    doc.setTextColor(...primaryColor);
    doc.text('Key Maintenance Performance Indicators', 14, currentY);
    currentY += 4;

    const cardWidth = 43;
    const cardHeight = 16;
    const cards = [
      { label: 'Total Faults', val: String(kpis.total) },
      { label: 'Relevant', val: String(kpis.relevant) },
      { label: 'Non-Relevant', val: String(kpis.nonRelevant) },
      { label: 'Avg TTR', val: formatMinutes(kpis.avgTTR) }
    ];

    cards.forEach((c, idx) => {
      const x = 14 + idx * (cardWidth + 3);
      doc.setFillColor(248, 250, 252);
      doc.setDrawColor(226, 232, 240);
      doc.roundedRect(x, currentY, cardWidth, cardHeight, 2, 2, 'FD');

      doc.setFont('helvetica', 'normal');
      doc.setFontSize(7.5);
      doc.setTextColor(100, 116, 139);
      doc.text(c.label.toUpperCase(), x + 4, currentY + 5);

      doc.setFont('helvetica', 'bold');
      doc.setFontSize(12);
      doc.setTextColor(...primaryColor);
      doc.text(c.val, x + 4, currentY + 12);
    });

    currentY += cardHeight + 8;
  }

  // 3. Report Specific Tables
  if (reportType === 'monthly') {
    // Breakdown by Equipment Type Table
    const eqCounts: Record<string, { count: number; downtime: number }> = {};
    equipmentTypes.forEach(t => { eqCounts[t.code] = { count: 0, downtime: 0 }; });
    faults.forEach(f => {
      const code = eqTypeMap.get(f.equipmentTypeId) || f.equipmentTypeId;
      if (!eqCounts[code]) eqCounts[code] = { count: 0, downtime: 0 };
      eqCounts[code].count += 1;
      eqCounts[code].downtime += f.downtimeMinutes;
    });

    const eqRows = Object.entries(eqCounts).map(([code, data]) => [
      code,
      String(data.count),
      formatMinutes(data.count > 0 ? Math.round(data.downtime / data.count) : 0),
      formatMinutes(data.downtime)
    ]);

    autoTable(doc, {
      startY: currentY,
      head: [['Equipment Type', 'Fault Count', 'Avg Downtime', 'Total Downtime']],
      body: eqRows,
      theme: 'grid',
      headStyles: { fillColor: [51, 65, 85], textColor: 255, fontStyle: 'bold', fontSize: 8 },
      bodyStyles: { fontSize: 8, textColor: 50 },
      margin: { left: 14, right: 14 }
    });

    currentY = (doc as any).lastAutoTable.finalY + 8;

    // Recurring Faults Table
    const descMap: Record<string, { desc: string; count: number; eq: string }> = {};
    faults.forEach(f => {
      const key = `${f.equipmentTypeId}_${f.faultDescription}`;
      if (!descMap[key]) {
        descMap[key] = {
          desc: f.faultDescription,
          count: 0,
          eq: eqTypeMap.get(f.equipmentTypeId) || f.equipmentTypeId
        };
      }
      descMap[key].count += 1;
    });
    const recurringRows = Object.values(descMap)
      .sort((a, b) => b.count - a.count)
      .slice(0, 5)
      .map(r => [r.eq, r.desc, String(r.count)]);

    if (recurringRows.length > 0) {
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(10);
      doc.setTextColor(...primaryColor);
      doc.text('Top Recurring Failures', 14, currentY);
      currentY += 3;

      autoTable(doc, {
        startY: currentY,
        head: [['Type', 'Fault Description', 'Occurrences']],
        body: recurringRows,
        theme: 'striped',
        headStyles: { fillColor: [71, 85, 105], textColor: 255, fontStyle: 'bold', fontSize: 8 },
        bodyStyles: { fontSize: 8 },
        margin: { left: 14, right: 14 }
      });
      currentY = (doc as any).lastAutoTable.finalY + 8;
    }
  }

  // 4. Detailed Faults Table
  const tableRows = faults.slice(0, 100).map(f => [
    f.callNumber || f.callId,
    `${f.reportDate}\n${f.reportTime}`,
    nodeMap.get(f.structureNodeId) || f.structureNodeId,
    `${eqTypeMap.get(f.equipmentTypeId) || f.equipmentTypeId}\n${f.equipmentNumber}`,
    f.faultDescription,
    f.assignedTechnicianName || '-',
    formatMinutes(f.ttrMinutes),
    f.relevantState,
    f.status
  ]);

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10);
  doc.setTextColor(...primaryColor);
  doc.text(
    reportType === 'monthly' ? 'Recent Maintenance Log' : 'Fault Records List',
    14,
    currentY
  );
  currentY += 3;

  autoTable(doc, {
    startY: currentY,
    head: [['Call No.', 'Date/Time', 'Location', 'Equip.', 'Description', 'Technician', 'TTR', 'Relevant', 'Status']],
    body: tableRows,
    theme: 'striped',
    headStyles: { fillColor: primaryColor, textColor: 255, fontStyle: 'bold', fontSize: 7.5 },
    bodyStyles: { fontSize: 7, textColor: 50 },
    columnStyles: {
      0: { cellWidth: 18 },
      1: { cellWidth: 20 },
      2: { cellWidth: 24 },
      3: { cellWidth: 22 },
      4: { cellWidth: 42 },
      5: { cellWidth: 22 },
      6: { cellWidth: 14 },
      7: { cellWidth: 18 },
      8: { cellWidth: 16 }
    },
    margin: { left: 14, right: 14 },
    didDrawPage: (data) => {
      // Footer page numbering
      const pageCount = (doc as any).internal.getNumberOfPages();
      doc.setFontSize(8);
      doc.setTextColor(148, 163, 184);
      doc.text(
        `Page ${data.pageNumber} of ${pageCount} — ApexCMMS Confidential Maintenance Report`,
        105,
        290,
        { align: 'center' }
      );
    }
  });

  const filename = `${title.toLowerCase().replace(/[^a-z0-9]/g, '_')}_${new Date().toISOString().slice(0, 10)}.pdf`;
  doc.save(filename);
}
